### ISSUE TITLE
ansible upgrade failing: nginx 502 bad gateway

### ISSUE THREAD

**Issue by claykimber** [LemmyNet/lemmy-ansible#100]
Hello and apologies if this has been reported already...I'm not seeing an issue for it.

The initial ansible install for 0.17.4 worked flawlessly.  Per the README, I did a git pull on this repo and ran ansible-playbook -i inventory/hosts lemmy.yml --become, which seemingly worked fine w/no errors.  However, I get an nginx 502 bad gateway error after the upgrade.  

docker logs returns:

thread 'main' panicked at 'Failed to load settings file, see documentation (https://join-lemmy.org/docs/en/administration/configuration.html): LemmyError { message: None, inner: "unknown field `setup`, expected one of `smtp_server`, `smtp_login`, `smtp_password`, `smtp_from_address`, `tls_type`" near 19:8, context: SpanTrace [] }', crates/utils/src/settings/mod.rs:20:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Portly8461** [comment]
I had similar. Remove the setup section from your config.hjson and re-push. Since you have already established an instance that section is likely not needed.

Removing the setup section for me resolved the issues.

**Comment by claykimber** [comment]
That worked, much appreciated.
