### ISSUE TITLE
Errors when uploading banners and icons after 0.18.0 upgrade.

### ISSUE THREAD

**Issue by SigurdVie** [LemmyNet/lemmy-ansible#104]
I'll make the issue here, as this happened after using lemmy-ansible to update my instance. (The instance was also of course made with ansible)

Whenever i want to upload a banner or icon to one of my instances i get this error in the bottom corner:
`SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON`

Is this a problem with ansible, or is this something i should put on the main lemmy repo?

**Comment by EuphoricPenguin** [comment]
I'm having a similar issue, and nothing I've tried so far with nginx configs has solved anything.

**Comment by ross-spencer** [comment]
My install was a bit of a mess after upgrading (connected to https://github.com/LemmyNet/lemmy-ansible/issues/103)

I found something wrong in the folder permissions and I followed the advice here which helped, but tbh, I'm not entirely sure what specific thing I did that helped. 

https://github.com/LemmyNet/lemmy/issues/832#issuecomment-648825946

**Comment by EuphoricPenguin** [comment]
> My install was a bit of a mess after upgrading (connected to https://github.com/LemmyNet/lemmy-ansible/issues/103)
> 
> I found something wrong in the folder permissions and I followed the advice here which helped, but tbh, I'm not entirely sure what specific thing I did that helped. 
> 
> https://github.com/LemmyNet/lemmy/issues/832#issuecomment-648825946

Do you remember which chmod commands you ran? I remember people mentioning one related to one of the pictrs folders, but I think I tried it and it didn't do anything. I'm running Lemmy as root, so I'm not sure how much file permissions would affect that.

**Comment by HopperMCS** [comment]
I am also having this issue. Took me wayyy too long to find this issue, hope it doesn't get buried

**Comment by dessalines** [comment]
https://github.com/LemmyNet/lemmy-ansible/issues/96

Also make sure you set the correct pictrs folder permissions (only necessary if you're doing a docker install, ansible does this for you) https://join-lemmy.org/docs/administration/install_docker.html#folder-permissions

**Comment by dessalines** [comment]
Stale issue. Feel free to re-open if its still a problem.
