### ISSUE TITLE
How to externalize pictrs configuration with ansible?

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ansible#109]
I'm very much not an ansible expert, so I could really use some help from @Nutomic or others on this one.

Currently pictrs is configured via env-vars, hard-coded into the `docker-compose.yml` . This isn't a good design, because the docker-compose is template file common to all deploys. Some deploys might use an s3 pictrs config, while others, the default file-based one.

Our option are:

- Figure out how to externalize the environment vars provided to pictrs, and include them in `inventory/host_vars/{{instance}}/` somehow.
- Make the `docker-compose.yml` custom for each install. I really don't like this one tho.

**Comment by mpraeger** [comment]
As you are already using ansible's `template` module for docker-compose.yml changing it to be configurable via host_vars seems like something to try before digging into pictrs and how to externalise its configuration is an unknown factor.

`docker-compose.yml` already contains [some pictrs configuration](https://github.com/LemmyNet/lemmy-ansible/blob/main/templates/docker-compose.yml#L57). Making that dynamic and configurable looks pretty straight forward. Which config options were you looking to externalise?

**Comment by dessalines** [comment]
A lot of its `S3` configuration settings, which should be optional. Essentially I need to provide a variable set of env vars to a specific container.

**Comment by Demigodrick** [comment]
You would need to add the following lines to the pictrs environment in docker-compose.yml:
`
      - PICTRS__STORE__TYPE=object_storage
      - PICTRS__STORE__ENDPOINT=<S3 endpoint>
      - PICTRS__STORE__BUCKET_NAME=<bucket name>
      - PICTRS__STORE__REGION=<region>
      - PICTRS__STORE__USE_PATH_STYLE=false 
      - PICTRS__STORE__ACCESS_KEY=<access key>
      - PICTRS__STORE__SECRET_KEY=<secret key>
`
However as dessalines has pointed out, you can't really make them variable because of the setup - two different compose files might be the option, or commenting the above lines out with a note to say only required if using external s3 storage.

**Comment by adambowles** [comment]
Could we use a script to take these configs from one .yml file and add them to the docker compose, such that the end user doesn't have to edit files tracked by git, causing potential issues in upgrades. I know that someone wishing to deploy a Lemmy instance should have a working knowledge of git..

Preferably this script would handle all the deploy steps outlined in the [readme](https://github.com/LemmyNet/lemmy-ansible#install)

**Comment by adambowles** [comment]
Started a PR to do like I suggested:  #129

**Comment by mpraeger** [comment]
@adambowles You can do what you're trying to do with ansible builtin functionality. The task is already using the `template` module, adding optional config is possible with jinja2. I started that over the weekend [here.](https://github.com/mpraeger/lemmy-ansible/commit/e5f9afc7ff0652567287e4177751ee2633d15bde)

**Comment by adambowles** [comment]
Yeah I'd rather do something with proper support than my hacky script 👍

**Comment by mpraeger** [comment]
Feel free to improve what I've done, I won't be able to continue until next week.

**Comment by adambowles** [comment]
Notice that my script also covers the manual steps in the readme (e.g. copy hosts file from examples). I'll look to incorporate the method you've outlined for templating the object store yaml

**Comment by ticoombs** [comment]
> I started that over the weekend [here.](https://github.com/mpraeger/lemmy-ansible/commit/e5f9afc7ff0652567287e4177751ee2633d15bde)

Is the most correct way to do it. If you don't think of them as env variables and think of them as a dict it makes more sense.

**Comment by dessalines** [comment]
@mpraeger thanks! Once it gets in a ready state, lmk, as this will be useful to a lot of lemmy installs.

**Comment by codyro** [comment]
I've added the logic (and a few other tweaks) discussed above (@mpraeger being the primary inspiration) in https://github.com/LemmyNet/lemmy-ansible/pull/160.

Any feedback is welcome and appreciated!
