### ISSUE TITLE
Set proper timezone

### ISSUE THREAD

**Issue by arnobnq** [LemmyNet/lemmy-ansible#113]
Hi

I've noticed that the docker containers don't use the correct timezone for my location (2 hours offset).

How would you go about changing that? 

I have tried setting `TZ=<Country>/<City>` in the  the docker-compose.yml template and running the playbook again, but it didn't have an effect. Am I missing something here?

Thanks !

**Comment by dessalines** [comment]
https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

Almost certainly a system configuration issue, nothing to do with lemmy or ansible.
