### ISSUE TITLE
Email - Cannot assign requested address

### ISSUE THREAD

**Issue by Al3xDaniels** [LemmyNet/lemmy-ansible#117]
I am setting up a new instance all is work except email functionality. Looking through my docker logs I am seeing the following. 
```
lemmy4funcom-postfix-1   | 2023-07-02T14:13:38.381790+00:00 88752f9cf6c6 postfix/smtp[139]: 3ED9EBD216: to=<xxxx@gmail.com>, relay=none, delay=60, delays=0.06/0.02/60/0, dsn=4.4.1, status=deferred (connect to alt2.gmail-smtp-in.l.google.com[2607:f8b0:4001:c56::1a]:25: Cannot assign requested address)

lemmy4funcom-postfix-1   | 2023-07-02T14:12:38.310009+00:00 88752f9cf6c6 postfix/qmgr[133]: 3ED9EBD216: from=<noreply@lemmy4fun.com>, size=1207, nrcpt=1 (queue active)

lemmy4funcom-postfix-1   | 2023-07-02T14:12:38.334818+00:00 88752f9cf6c6 postfix/smtp[139]: connect to gmail-smtp-in.l.google.com[2607:f8b0:4023:c0d::1a]:25: Cannot assign requested address

lemmy4funcom-postfix-1   | 2023-07-02T14:13:08.342871+00:00 88752f9cf6c6 postfix/smtp[139]: connect to gmail-smtp-in.l.google.com[142.250.141.26]:25: Connection timed out

lemmy4funcom-postfix-1   | 2023-07-02T14:13:08.342985+00:00 88752f9cf6c6 postfix/smtp[139]: connect to alt1.gmail-smtp-in.l.google.com[2607:f8b0:4003:c15::1b]:25: Cannot assign requested address
```
For the record xxx@gmail.com is just me hiding my email in this post.

**Comment by ross-spencer** [comment]
hi @Al3xDaniels do you have an SPF record setup for your domain? The barrier to sending emails to GMail vs other servers is a little higher: https://sitehost.nz/blog/gmail-spf-record

You should be able to read via here if it is: https://mxtoolbox.com/

**Comment by Al3xDaniels** [comment]
It would appear the issue is coming from Azure actually to prevent spam by default port 25 is blocked.

**Comment by mattjhill** [comment]
@subashz that's correct I just ran into the same issue with Lightsail. [Per they're support](https://repost.aws/knowledge-center/lightsail-port-25-throttle), I filed a ticket and was denied opening the port and requested to consider using SES. So, it seems like Lightsail isn't going to work unless there is a way to change the email service.

**Comment by mattjhill** [comment]
Can that be done just via the config file?

**Comment by ticoombs** [comment]
#close Resolved/Offtopic/not related to a lemmy-ansible code issue.
