### ISSUE TITLE
Your Lemmy-Support link is to a lemmy server that is closed...

### ISSUE THREAD

**Issue by akzmonster** [LemmyNet/lemmy-ansible#121]
I need help. The provided guides are unhelpful. The link to the Lemmy Support lemmy.ml is to a lemmy server that is closed and not taking logins. I created on at lemmy.world and it doesn't work.

I really want to run a lemmy server but this is honestly a trash experience. I love linux but god do I fucking hate linux.

**Comment by ross-spencer** [comment]
@akzmonster it looks like you can sign up here: https://lemmy.ml/signup

**Comment by akzmonster** [comment]
> @akzmonster it looks like you can sign up here: https://lemmy.ml/signup

Have you tried to do this? For me it just says "Registration Closed". I created a Lemmy.world account since this server was federated and it still refuses connection.

**Comment by ross-spencer** [comment]
> Have you tried to do this? For me it just says "Registration Closed". 

I haven't so I guess it probably is closed for some reason, maybe others can confirm?

**Comment by slrgt** [comment]
> > @akzmonster it looks like you can sign up here: https://lemmy.ml/signup
> 
> Have you tried to do this? For me it just says "Registration Closed". I created a Lemmy.world account since this server was federated and it still refuses connection.

registrations are closed to prevent bots and the server from becoming too large. You can still post on to the support community from the lemmy.world or any server you registered on by going to the server (i.e. lemmy.world) clicking Create a Post and then in the Community section choose Lemmy Support
