### ISSUE TITLE
Ansible setup has hard dependency on amd64

### ISSUE THREAD

**Issue by iheart2code** [LemmyNet/lemmy-ansible#130]
The following hard-coded instance of `amd64` means that installation of Docker from apt repository will fail on devices like RPI 4.

https://github.com/LemmyNet/lemmy-ansible/blob/41f5f55cf70d4d7790466566d1dc0eafbc1be768/lemmy.yml#L69C30-L69C35

This will result in the following output when trying to `sudo apt install docker-ce`:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  docker-ce-cli:amd64

E: Package 'docker-ce' has no installation candidate
```

**Comment by iheart2code** [comment]
Possibly related to #123 ?

**Comment by iheart2code** [comment]
Temporary workaround -- change the line to match these contents:

```
            repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
```

**Comment by eslerm** [comment]
Could you please save the following playbook to your lemmy-ansible directory as `ansible-facts.yaml` and run `ansible-playbook -i inventory/hosts ansible-facts.yaml --become --ask-become-pass|grep -E 'arch|dist'` ?
```
---
- hosts: all

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
```
