### ISSUE TITLE
Duplicate headers between external and internal nginx configs

### ISSUE THREAD

**Issue by ndanyluk** [LemmyNet/lemmy-ansible#143]
Hi, unsure if this is an issue, but I noticed that my Lemmy instance was getting flagged on the Mozilla Observatory for unrecognized X-Content-Type-Options, X-Frame-Options and X-XSS-Protection headers which is weird since it definitely is in the config on this repo.

Looking at what it sees when it scans my site I realized that these headers appear in both configs and this is what is tripping up Mozilla. I don't know if this matters in practice.

Example headers after upgrade to 0.18.3:
x-content-type-options: nosniff, nosniff
x-frame-options: SAMEORIGIN, DENY
x-xss-protection: 1; mode=block, 1; mode=block

I can submit a PR modifying the config, but would it be better to remove these headers from the internal or external config? It seems to only matter for the X-Frame-Options header.

**Comment by dessalines** [comment]
Hrm. I suppose either one works, but the internal one would be preferred.
