### ISSUE TITLE
reload with override cache shows me that i am no longer logged

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ansible#146]
Hello all,

I didn't use the ansilbe script but the files from it to create my lemmy instance. I followed these instructions: https://join-lemmy.org/docs/administration/install_docker.html

**Anyway, about the problem:**
When I reload the page using (override cache), it looks to me like I am not logged in. I then have to reload the page once so that I can interact with lemmy normally again.

I have a second instance from an older installation, this one doesn't have the nginx docker container yet, is there something wrong with it?

**Comment by Tealk** [comment]
so after 24h it seems to have calmed down.

**Comment by ticoombs** [comment]
This would not be specific to the ansible-code but to lemmy itself as you yourself said you did not use the ansible code to create your infrastructure. If this is still an issue it would be better suited to the Lemmy repo

#close

**Comment by Tealk** [comment]
on the installation guide is referenced to this repo, that's why i opened this here because the docker-compose file here is structured differently than in the lemmy repo

**Comment by dessalines** [comment]
I'm not sure what we could do here about that. Its likely a lemmy-ui issue.
