### ISSUE TITLE
Strange redirect rule on slash at the end of URL

### ISSUE THREAD

**Issue by SorteKanin** [LemmyNet/lemmy-ansible#149]
Go to `https://lemmy.ml/c/announcements` and everything works as you expect.

However, if you go to `https://lemmy.ml/c/announcements/` (notice the added slash at the end), you are redirected to `https://lemmy.ml:8536/c/announcements`, which fails to load.

I'm guessing this has something to do with this rule in the internal nginx configuration:
```
        # frontend general requests
        location / {
            proxy_pass $proxpass;
            rewrite ^(.+)/+$ $1 permanent;
        }
```

But I'm not sure. Also not sure how to fix it. Ideally it should redirect to `https://lemmy.ml/c/announcements` without the specified port.

**Comment by codyro** [comment]
You are correct in your assumption. I've modified the rules slightly to address this, however I was only able to test briefly. Would you (and others) mind giving this rule a test? If it works I can make a PR.

**nginx_internal.conf**

Remove:

```
        # frontend general requests
        location / {
            proxy_pass $proxpass;
            rewrite ^(.+)/+$ $1 permanent;
        }
```

Add/Replace with:

```
        # frontend general requests
        location / {
            # If there's a trailing slash, rewrite the URL without redirecting
            rewrite ^(.+)/+$ $1 break;

            # Then, proxy to the appropriate upstream based on $proxpass
            proxy_pass $proxpass;
        }

```

**Comment by dessalines** [comment]
Fixed above.
