### ISSUE TITLE
How to get SMTP working

### ISSUE THREAD

**Issue by akzmonster** [LemmyNet/lemmy-ansible#154]
Maybe I'm doing it wrong, but I need to get SMTP working. I'm using Digital Ocean and they block port 25 (I think). So I've read that I should use port 465 instead. But the guide doesn't exactly say how to do this. I have found a few places that identify the "postfix" port and I have changed that from 25 to 465, but nothing works.

Is there any chance you can elaborate on how to implement port 465 for SMTP? Or literally any method that gets emails working.

Thanks!

**Comment by akzmonster** [comment]
Seriously, any method that gets email working is fine. I don't have a preference. I just need it to work.

**Comment by ross-spencer** [comment]
@akzmonster what error messages are you seeing?

**Comment by akzmonster** [comment]
No error message. When I select "forgot password" and enter my email address, it does nothing. No message, no update. Nothing received in junk, spam, trash - just nothing.

It does nothing.

I think I changed the port to 465 since DO blocks port 25, but I don't know since this isn't documented anywhere. The documentation on this whole process is lacking, severely.

**Comment by ross-spencer** [comment]
> The documentation on this whole process is lacking, severely.

I don't necessarily disagree, but you're essentially setting up email for the system as a whole. If you can find some documentation on sending email from a Linux command line it may help. Debugging from Lemmy itself is going to be a bit harder.

**Comment by akzmonster** [comment]
I get your point, but this conversation sort of proves mine:

> you're essentially setting up email for the system as a whole

> if you are not using the postfix container

I would love to use this "postfix container", but there is no direction about how to do that.

**Comment by dessalines** [comment]
The locally running postfix doesn't need a TLS connection, it works fine as is. The issue is that some email services may be blocking your domain, and sending those mails to spam.

If you'd like to use your own email instead of a local postfix one, @ticoombs showed how.

**Comment by akzmonster** [comment]
> sending those mails to spam.

No, I've checked. As stated above, no emails are sent. Not to spam, not to junk, not to trash. Nothing is sent.

**Comment by akzmonster** [comment]
> Complaining about the documentation won't fix the problem.
> 
> All SMTP details if you are not using the postfix container can be sorted by editing `host_vars/<domain>/config.hjson`
> 
> ```
> email: {
>     smtp_server: "domain:port"
>     smtp_from_address: "noreply@{{ domain }}"
>     smtp_login: "youremail"
>     smtp_password: "yourpassword"
>     tls_type: "tls"
> }
> ```
> 
> I use port 465 with TLS
> 
> #close

I tried this. Changed 25 to 465. Still nothing.

**Comment by dessalines** [comment]
Could you post the postfix logs?

`sudo docker compose logs postfix`

Its likely that your email service is blocking content from certain domains. 

postfix doesn't use TLS. If you want to use your own email service, then you need to input those credentials in the config.
