### ISSUE TITLE
Internal nginx not sending headers to backend on GET

### ISSUE THREAD

**Issue by ceandreasen** [LemmyNet/lemmy-ansible#155]
[Per the nginx documentation](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header), proxy_set_header directives are only inherited from the previous config level if none are specified at the current level. 

So in this snippet from the nginx_internal.conf template, X-Real-IP, Host, and X-Forwarded-For are set at the server{ } level and are inherited by some of the location blocks and not others. Specifically, the backend redirect at the bottom contains other proxy_set_header directives, that will inhibit the inheritance.

```
    server {

        <*snip*>

        # Send actual client IP upstream
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # frontend general requests
        location / {
            proxy_pass $proxpass;
            rewrite ^(.+)/+$ $1 permanent;
        }

        # security.txt
        location = /.well-known/security.txt {
            proxy_pass "http://lemmy-ui";
        }

        # backend
        location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known) {
            proxy_pass "http://lemmy";

            # proxy common stuff
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
```

**Comment by dessalines** [comment]
Could you do a PR for this? Thanks
