### ISSUE TITLE
Occasional crashes on nginx_internal `proxy`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ansible#164]
Occasionally, a server will crash, return a 502 gateway, and by restarting the `proxy` service in docker,  its resolved.

I'll try to record some logs next time this happens.

Some possible fixes here, and I'm testing one of them out on lemmy.ml rn:

https://stackoverflow.com/questions/32845674/setup-nginx-not-to-crash-if-host-in-upstream-is-not-found

**Comment by codyro** [comment]
Have you had any issues with lemmy.ml since you've been using https://github.com/LemmyNet/lemmy-ansible/pull/165? If not, this should be good to close :).

**Comment by dessalines** [comment]
No issues, so its good to close.
