### ISSUE TITLE
Update README `Upgrading` section, add check?

### ISSUE THREAD

**Issue by codyro** [LemmyNet/lemmy-ansible#170]
Improve the `Upgrading` section of the README to reflect the changes/addition of the `vars.yml` file & renaming of the `passwords/postgres` file to `passwords/postgres.psk` file for users upgrading from versions that do not have this file. 

In addition to this (or alternatively), we could have the playbooks do a sanity check and notify the user if it's missing in the `pre_tasks` or elsewhere.

Refs
* https://github.com/LemmyNet/lemmy-ansible/issues/169#issuecomment-1718288517

**Comment by ticoombs** [comment]
FWIW, I think the pre_tasks checks should exist, and pointing people to the readme's especially regards to the (new?) upgrade procedure.

**Comment by codyro** [comment]
Done in #172
