### ISSUE TITLE
Create tags and update documentation 

### ISSUE THREAD

**Issue by ticoombs** [LemmyNet/lemmy-ansible#171]
Now that we are merging features, we are unfortunately creating more issues because of the breaking changes. 

Moving to tags will allow us to provide a solution so people can update to the latest versions without incurring issues. 

Create tags for `78af02b5e83bc815e549587bb22952256363fc23` (https://github.com/LemmyNet/lemmy-ansible/tree/78af02b5e83bc815e549587bb22952256363fc23) which is the latest "stable" before our variable changes happened (unless I'm wrong)

**Comment by codyro** [comment]
I think what you laid out here, and https://github.com/LemmyNet/lemmy-ansible/issues/169#issuecomment-1718632614 seems reasonable. 

It looks like the maintainers used tags when they updated the `VERSION` file to match the version of Lemmy it represented. We should ensure we don't conflict with their workflows. 

However, I see `@dessalines` thumbed this up already, so we are likely safe to proceed. 

Do you want to do what you laid out in your comment?

I have a semi-related change in https://github.com/LemmyNet/lemmy-ansible/issues/170 we can toss or merge to fix the `vars.yml` issue as well.

**Comment by ticoombs** [comment]
Tag pushed. I probably wont get to doing the documentation today. If you have time that would be welcome. 
I pushed `1.1.0` (without `v`) as I honestly didn't even see the previous tags, so at least this way we can keep a similar pattern while "migrating" everyone to using tags.

**Comment by codyro** [comment]
A new version of Lemmy was released, and a tag was created alongside it: https://github.com/LemmyNet/lemmy-ansible/releases/tag/0.18.5

We need to document our changes soon and probably create a new tag for the latest version of the playbooks/Lemmy. 

I propose we create a new tag (as per semver.org) alongside a `CHANGELOG` file with the changes from `1.1.0` to date. Then I guess we tag alongside the developers when they bump the `VERSION`?

Let me know your thoughts and I can start with that.

**Comment by ticoombs** [comment]
Yes great idea! Please do. 

Also we need to update the initial `git clone` command to checkout the "latest" version.
