### ISSUE TITLE
ERROR! 'notify' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by pixlguru** [LemmyNet/lemmy-ansible#177]
Update failed 0.18.4 -> 9.18.5

I followed the update instructions, 
- renamed postgres.psk
- copied vars.yml

`
ansible-playbook -i inventory/hosts lemmy.yml --become`

```
ERROR! 'notify' is not a valid attribute for a Block

The error appears to be in '/home/user/workspace/folder/lemmy-ansible/lemmy.yml': line 190, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


        - name: Set up nginx sites-enabled symlink
          ^ here

```

**Comment by codyro** [comment]
What version of Ansible are you on (`ansible --version`)? Using `notify` with a `block` is supported on the latest versions:

https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#block

Can you update Ansible and see if it works for you?

**Comment by pixlguru** [comment]
> Can you update Ansible and see if it works for you?

It does, thanks a lot!

**Comment by omalaspinas** [comment]
I have the same error when upgrading to lemmy-ansible version 1.2.0. Working on Ubuntu 22.04. Ansible 2.10.8.

Last time I made an update was a bit after the release of the lemmy version to 0.18.4 (don't know the exact commit though).

Any idea?

**Comment by codyro** [comment]
It looks like support for this was added after Ansible 2.10. If you upgrade to the latest version of Ansible, this will work. I'll have the documentation updated with the appropriate Ansible version once I confirm when this was supported.

You can install the latest version quickly from pip by running `python3 -m pip install ansible` (this should grab `2.15`, which does support `notify` usage in `block`s.

**Comment by codyro** [comment]
Looks like it was added in 2.11 (Ansible 4).

Ref: 
* https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-community-changelogs
* https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst#L7552

**Comment by omalaspinas** [comment]
You are right. It's working. Thank  you!
