### ISSUE TITLE
Fix ansible-lint issue on `examples/vars.yml` causing CI failure

### ISSUE THREAD

**Issue by codyro** [LemmyNet/lemmy-ansible#184]
Either need to move it to a folding block or `noqa` it.

```
WARNING  Listing 1 violation(s) that are fatal
yaml[line-length]: Line too long (166 > 160 characters)
examples/vars.yml:3
```

**Comment by ticoombs** [comment]
+1 `noqa` for the password lines only. 

Do we not build against PRs? This should have been sorted in the PR before merging.

**Comment by codyro** [comment]
The [initial commit](https://github.com/LemmyNet/lemmy-ansible/pull/175/commits/b6e703fe0dcf5d3ac3c6fd23dd17ed1d666fffbd) passed CI fine because it didn't run against `vars.yml`. While that PR was pending review, I merged in https://github.com/LemmyNet/lemmy-ansible/commit/963ab7b9f58f7b6b907132464936f82577631ed8 to add `vars.yml` to the CI pipeline.

The initial PR had no additional commits, so the new pipeline didn't run against `vars.yml`.

**Comment by codyro** [comment]
Fixed in https://github.com/LemmyNet/lemmy-ansible/pull/186
