### ISSUE TITLE
New installation failing

### ISSUE THREAD

**Issue by 2ro** [LemmyNet/lemmy-ansible#19]
`TASK [start docker-compose] ***************************************************************************************************
fatal: [root@domain.com]: FAILED! => {"changed": false, "errors": [], "module_stderr": "Recreating 33ed084a4353_domaincom_pictrs_1 ... \nRecreating 12eff598f1bf_domaincom_postgres_1 ... \nStarting domaincom_postfix_1                 ... \n", "module_stdout": "", "msg": "Error starting project a bytes-like object is required, not 'str'"}`

replaced my real domain with placeholder "domain.com" for the sake of privacy

Debian 11 x64 updated install

**Comment by dessalines** [comment]
Doesn't look like a new installation, because its recreating the containers. You might need to remove the old ones. 

Also after searching for that error, its either a python version or docker compose issue. Try commenting / uncommenting the python line in ansible.cfg as the readme here suggests.

**Comment by 2ro** [comment]
That was just a second time running it, it's a fresh install.

I tried commenting the python line to no avail. Thanks for your help so far. I'm still unable to install with ansible.

**Comment by dessalines** [comment]
Post your hosts and config.hjson , but as I said, when I searched for that error, it seemed to be a python issue on your system.

**Comment by 2ro** [comment]
Working now.

Debian 11 x64 updated install -> Ubuntu 20.04 updated install worked out the box.

**Comment by jorgesumle** [comment]
Followed the readme instructions, but it fails:

```
$ ansible-playbook -i inventory/hosts lemmy.yml --become --ask-become-pass
BECOME password: 

PLAY [all] ****************************************************************************************************************************************************************************

TASK [check lemmy_base_dir] ***********************************************************************************************************************************************************
skipping: [root@freakspot.net]

TASK [install python for Ansible] *****************************************************************************************************************************************************
fatal: [root@freakspot.net]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@freakspot.net: Permission denied (publickey,password).", "unreachable": true}

PLAY RECAP ****************************************************************************************************************************************************************************
root@freakspot.net         : ok=0    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0   
```

I can connect to the server I provided via ssh. Here is the content of `inventory/hosts`:

```
[lemmy]
# to get started, copy this file to `inventory` and adjust the values below.
# - `myuser@example.com`: replace with the destination you use to connect to your server via ssh
# - `domain=example.com`: replace `example.com` with your lemmy domain
# - `letsencrypt_contact_email=your@email.com` replace `your@email.com` with your email address,
#                                              to get notifications if your ssl cert expires
# - `lemmy_base_dir=/srv/lemmy`: the location on the server where lemmy can be installed, can be any folder
#                                if you are upgrading from a previous version, set this to `/lemmy`
# - `lemmy_version`: <Optional> The back end version.
# - `lemmy_ui_version`: <Optional> overrides the front end version.
root@freakspot.net domain=lemido.freakspot.net letsencrypt_contact_email=jorgesumle@freakspot.net lemmy_base_dir=/srv/lemmy

[all:vars]
ansible_connection=ssh
```

**Comment by dessalines** [comment]
Maybe don't use --become if you're already root? This doesn't have to do with lemmy, but with your ansible ssh connection.
