### ISSUE TITLE
issue with postgree password with playbook 1.2.0 ?

### ISSUE THREAD

**Issue by tifriis208** [LemmyNet/lemmy-ansible#191]
Hello,

I try a from scratch install of lemmy on ubuntu 22.04.
Playbook runs withtout issue, but when I try to connect to my instance, I get the following message on my browser:
_Erreur !
Une erreur s'est produite sur le serveur. Essayez d'actualiser votre navigateur. Si cela ne fonctionne pas, revenez plus tard. Si le problème persiste, vous pouvez demander de l'aide à la [Communauté d'assistance Lemmy](https://lemmy.ml/c/lemmy_support) ou à la [Groupe Matrix Lemmy](https://lemmy.ml/c/lemmy_support)._

In my logs, I got :
```
root@xxx:/srv/lemmy/xxxxxx# docker-compose logs -f lemmy
Attaching to lienslowtechfr_lemmy_1
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:XBBmfAp9PNLJuxv56eWY@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     | 	Is the server running on host "postgres" (172.18.0.2) and accepting
lemmy_1     | 	TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:XBBmfAp9PNLJuxv56eWY@postgres:5432/lemmy: could not connect to server: Connection refused
```

Seems like an issue to connect to postgree, maybe a password issue ?

Never have this issue before.

Thanks :)

**Comment by codyro** [comment]
It doesn't look like the PostgreSQL VM is running. Can you run the following and see if it's running and or constantly starting/crashing?

`docker ps -a | grep postgres`

You can also check the Docker logs for the instance by pulling the VM ID from the above command and running:

`docker logs <VMID>`

**Comment by codyro** [comment]
Actually,

Can you clarify if you checked out the `main` branch or the `1.2.0` tag? This should already be fixed and or fixed in `1.2.1` (https://github.com/LemmyNet/lemmy-ansible/pull/183) when it gets pushed.

Please check this issue and see if it helps: https://github.com/LemmyNet/lemmy-ansible/issues/190

**Comment by mszaro** [comment]
I'm also seeing the same issue, with `main` checked out:

```
$ sudo docker ps -a | grep postgres
fd8bbc171ad1   postgres:15-alpine           "docker-entrypoint.s…"   32 minutes ago   Up 32 minutes                     5432/tcp 
```                                            

and yet:

```
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:redacted@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     |   Is the server running on host "postgres" (172.20.0.5) and accepting
lemmy_1     |   TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is after appending `listen_addresses = '*'` to `customPostgres.conf`.

**Comment by codyro** [comment]
It sounds like the Postgres container isn't running. Can you pull the logs from that container so we can see why it's having difficulty starting? 

Thanks!

**Comment by codyro** [comment]
This is due to a bad configuration line in the `customPostgres.conf` file. It seems to have went unnoticed for awhile due to #183. 

```
2023-10-17 01:32:35.372 GMT [1] LOG:  unrecognized configuration parameter "temp_file_size" in file "/etc/postgresql.conf" line 27
2023-10-17 01:32:35.372 GMT [1] FATAL:  configuration file "/etc/postgresql.conf" contains errors
```

Comment out the `temp_file_size=1G` and the container should start.

**Comment by tifriis208** [comment]
Thanks for your return. @codyro , I got temp_file_size=1G in my customPostgresql.conf. I will try tonight to install from scratch without this option and let you know.

**Comment by mszaro** [comment]
> This is due to a bad configuration line in the `customPostgres.conf` file. It seems to have went unnoticed for awhile due to #183.
> 
> ```
> 2023-10-17 01:32:35.372 GMT [1] LOG:  unrecognized configuration parameter "temp_file_size" in file "/etc/postgresql.conf" line 27
> 2023-10-17 01:32:35.372 GMT [1] FATAL:  configuration file "/etc/postgresql.conf" contains errors
> ```
> 
> Comment out the `temp_file_size=1G` and the container should start. Would you mind letting me know if that fixes your issue @tifriis208 @mszaro?

I didn't have that file in my customPostgres.conf, so this change had no effect for me. The Postgres container appears to be running in `docker ps` but still having the same panic.

**Comment by dessalines** [comment]
What's the error?

**Comment by mszaro** [comment]
> What's the error?

Still the same one: https://github.com/LemmyNet/lemmy-ansible/issues/191#issuecomment-1765072956. Thanks in advance for chiming in!

**Comment by codyro** [comment]
> > What's the error?
> 
> 
> 
> Still the same one: https://github.com/LemmyNet/lemmy-ansible/issues/191#issuecomment-1765072956. Thanks in advance for chiming in!

Can you provide the logs to the Postgres container? 

`docker logs fd8bbc171ad1` (replace the container ID with your Postgres one if it changed from your earlier output).

**Comment by tifriis208** [comment]
For me it's now ok using the main branch on a fresh install. No more issue :)  @codyro, thanks for your help !

**Comment by mszaro** [comment]
> Can you provide the logs to the Postgres container?
```

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-10-16 18:03:42.979 GMT [1] LOG:  starting PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-10-16 18:03:42.979 GMT [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-10-16 18:03:42.979 GMT [1] LOG:  could not bind IPv6 address "::1": Address not available
2023-10-16 18:03:42.980 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-16 18:03:42.983 GMT [24] LOG:  database system was shut down at 2023-10-16 18:03:41 GMT
2023-10-16 18:03:42.989 GMT [1] LOG:  database system is ready to accept connections
2023-10-16 18:08:43.081 GMT [22] LOG:  checkpoint starting: time
2023-10-16 18:08:43.085 GMT [22] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.005 s; sync files=3, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
```

**Comment by codyro** [comment]
```
2023-10-16 18:03:42.979 GMT [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
```

This indicates that your Postgres configuration doesn't have the proper `listen_address` set. It should be listening on `0.0.0.0`, not `127.0.0.1`. Please double-check the `postgresql.conf` being used/mounted in the container. 

For reference, this is what it should look like:

```
2023-10-18 17:24:57.808 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
```

**Comment by mszaro** [comment]
> ```
> 2023-10-16 18:03:42.979 GMT [1] LOG:  listening on IPv4 address "127.0.0.1", port 5432
> ```
> 
> This indicates that your Postgres configuration doesn't have the proper `listen_address` set. It should be listening on `0.0.0.0`, not `127.0.0.1`. Please double-check the `postgresql.conf` being used/mounted in the container.
> 
> For reference, this is what it should look like:
> 
> ```
> 2023-10-18 17:24:57.808 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> ```

Thanks Cody. I set `listen_addresses` explicitly to `0.0.0.0` instead of `*` and my instance seems to be back to life.
