### ISSUE TITLE
Update to 0.19.0 failed

### ISSUE THREAD

**Issue by pixlguru** [LemmyNet/lemmy-ansible#207]
from the lemmy-container  log

`: LemmyError { message: Unknown("\"unknown field `cache_remote_images`, expected one of `url`, `api_key`, `cache_external_link_previews`, `upload_timeout`\" near 13:24"), inner: "unknown field `cache_remote_images`, expected one of `url`, `api_key`, `cache_external_link_previews`, `upload_timeout`" near 13:24, context: SpanTrace [] }', crates/utils/src/settings/mod.rs:20:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by dessalines** [comment]
That config setting name got changed: https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson#L54

Its not in this repo, and isn't a default, so there's nothing we can do from here.
