### ISSUE TITLE
Issues upgrading from 0.18.3 to 0.18.5 - Failed to lock apt for exclusive operation

### ISSUE THREAD

**Issue by RyantHults** [LemmyNet/lemmy-ansible#216]
Trying to update my Lemmy install from 0.18.3. 
Started off by trying to upgrade from 0.18.3 to 0.18.5. 
I followed the steps from https://github.com/LemmyNet/lemmy-ansible#upgrading for this process and am now trying to run my regular deployment command `ansible-playbook -i inventory/hosts lemmy.yml --become-user lemmy-admin --ask-become-pass`

It gets to the `install aptitude` task and throws the following error
`fatal: [lemmy-admin@domain.tld]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)"}`

searching around, this appears to be a common ansible issue, but all of the common solutions don't seem to work.
what I've tried so far:
* adding `become: yes` to the `install aptitude` task
* making the `update_cache: yes` it's own separate step in the task
* running `chmod 775 -r /var/lib/apt/lists/` 

All still result in the same error. My lemmy-admin account is able to run sudo.
Any thoughts on how to fix this?

**Comment by sanatsathaye** [comment]
Running `chmod` to change permissions of system folders isn't recommended at all... You need to use `become` along with `become-user`.

`ansible-playbook -i inventory/hosts lemmy.yml --become --become-user lemmy-admin --ask-become-pass`

**Comment by sanatsathaye** [comment]
Does `--become-user` even work without `--become`? Both are required from what I recall.

Why not just set up passwordless ssh from your source system directly to `lemmy-admin`? Will be easier to manage.

**Comment by ticoombs** [comment]
> Could not open lock file /var/lib/apt/lists/lock 

This is normally because apt is already running on the system. But as you have shown you can still have problems when you are running as a non-root user. 
We have since removed the `install aptitude` item and as such this should no longer be an issue.

If you believe the issue still is an issue, please let us know.
