### ISSUE TITLE
lemmy.yml giving syntax error (I think) when trying to run

### ISSUE THREAD

**Issue by 3nderall** [LemmyNet/lemmy-ansible#219]
I get the error
```
ERROR! couldn't resolve module/action 'community.docker.docker_compose'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/myname/lemmy/lemmy-ansible/lemmy.yml': line 257, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Start docker-compose
      ^ here
```
when I try to run lemmy.yml. I've looked at the yml file but I'm new to ansible and it seems to be the same as the rest of the lines. How do I fix it? I haven't edited it at all

**Comment by codyro** [comment]
Please see if this resolves your issue:

```shell
ansible-galaxy collection install community.docker
```

We need to update `requirements.yml` with `community.docker`.

**Comment by 3nderall** [comment]
It worked thanks. Is there a way to disable lets encrypt and change the ports because I have nginx proxy manager set up with all that already.

**Comment by 3nderall** [comment]
fixed, thanks
