### ISSUE TITLE
Lemmy-ui ports configuration when setting up with docker and reverse proxy is a bit confusing. 

### ISSUE THREAD

**Issue by mazury** [LemmyNet/lemmy-ansible#224]
Specifically lemmy-ui ports. 1234 and 1236. Couldn't we just use one? Sometimes it's one or the other. Check nginx configuration file and docker compose. Also env variables.

**Comment by dessalines** [comment]
Those two are necessary because 1234 is for the UI only, while 1236 is for the external nginx.

UI: 1234

BE: 8536

Nginx Proxy : 1236
