### ISSUE TITLE
On next release, include upgrade instructions for postgres 15 -> 16

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ansible#227]
This is unfortunately necessary due to a postgres 15 memory leak: https://github.com/LemmyNet/lemmy/issues/4406

This PR has the file: https://github.com/LemmyNet/lemmy/pull/4426/files#diff-4bb683dcf59cc3a55cf3b7c6f0b6a202149806f28f6ab704a83050d7d3aabf6c

Once that's merged, we need to make sure to  have instructions for the upgrade on the next lemmy-ansible release.

**Comment by ticoombs** [comment]
So this also removes the need to have `jit = no` in our customPostgres file too.

**Comment by dessalines** [comment]
I don't know enough about that setting to say if we should keep / remove, but I'd say pry remove.

**Comment by ticoombs** [comment]
lemmy.cafe dev/admins "confirmed" that the leak no longer is present when using `jit=no` so we can get rid of that too.
