### ISSUE TITLE
not currently on a branch

### ISSUE THREAD

**Issue by vengefulpunk** [LemmyNet/lemmy-ansible#233]
I am attempting to start the upgrade process from 1.2.1 to 1.3.0, but I've encountered an error.

git pull && git checkout 1.3.0

When I run that, I am receiving this error now.

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

I have already upgraded Lemmy a few times before, and it has never come up with a branch issue in the past. I went ahead and ran. 

git pull origin main

But it still gives the same error. I don't know what I'm missing to set the branch again.  

Thanks!

**Comment by vengefulpunk** [comment]
I think I shouldn't have been working on this yesterday.

ran git checkout main and git pull and I'm all good.

**Comment by ticoombs** [comment]
I'll probably add the following:

`git checkout main && git pull && git checkout 1.3.0`

As when you do: git checkout <version> you checkout a specific commit (tag), and so you are not technically on a branch. So people like you when they come to updating to the next version will find themselves "not on a branch"
