### ISSUE TITLE
Problems migrating 0.13.3 to 0.13.5

### ISSUE THREAD

**Issue by pixlguru** [LemmyNet/lemmy-ansible#4]
`fatal: [feddit@feddit.de]: FAILED! => {"changed": true, "cmd": "nginx -s reload", "delta": "0:00:00.021904", "end": "2021-10-30 08:15:57.700702", "msg": "non-zero return code", "rc": 1, "start": "2021-10-30 08:15:57.678798", "stderr": "nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/feddit.de.conf:117", "stderr_lines": ["nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/feddit.de.conf:117"], "stdout": "", "stdout_lines": []}`

so i guess it should be
`access_log /var/log/nginx/access.log lemmy_main;`

after that it throws:
`fatal: [feddit@feddit.de]: FAILED! => {"changed": true, "cmd": "nginx -s reload", "delta": "0:00:00.020002", "end": "2021-10-30 08:19:06.509913", "msg": "non-zero return code", "rc": 1, "start": "2021-10-30 08:19:06.489911", "stderr": "nginx: [emerg] limit_req_zone \"lemmy_ratelimit\" is already bound to key \"$binary_remote_addr\" in /etc/nginx/sites-enabled/lemmy.conf:1", "stderr_lines": ["nginx: [emerg] limit_req_zone \"lemmy_ratelimit\" is already bound to key \"$binary_remote_addr\" in /etc/nginx/sites-enabled/lemmy.conf:1"], "stdout": "", "stdout_lines": []}`

**Comment by dessalines** [comment]
@Nutomic have you ever run into this before?

**Comment by pixlguru** [comment]
one prolem solved, seems the old
`/etc/nginx/sites-enabled/lemmy.conf`
was conflicting with a new
`/etc/nginx/sites-enabled/<your-domain>.conf`

but it is still  pulling 0.13.3 BE/UI

**Comment by Nutomic** [comment]
You're right, and everyone that switches from the previous playbook to this one will run into the same problem. Maybe we should add an ansible task which removes that file (or moves it to sites-available).

**Comment by spa086** [comment]
In new install have a some problem. 

fatal: [root@fwz.ru]: FAILED! => {"changed": true, "cmd": "nginx -s reload", "delta": "0:00:00.072777", "end": "2021-11-04 19:07:41.321895", "msg": "non-zero return code", "rc": 1, "start": "2021-11-04 19:07:41.249118", "stderr": "nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/fwz.ru.conf:117", "stderr_lines": ["nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/fwz.ru.conf:117"], "stdout": "", "stdout_lines": []}

What should i do?

**Comment by Nutomic** [comment]
@spa086 Your errors look different, it seems like there is something wrong in the two files it mentions (fwz.ru.conf and loc.org.conf). Either delete them, or move them somewhere else (eg sites-available, then they will be ignored).

**Comment by pixlguru** [comment]
@spa086 @Nutomic 
check 
`/templates/nginx.conf`
lines 115, 177,
like i mentioned in the first post.

**Comment by spa086** [comment]
@Nutomic 
fatal: [lem@fwz.ru]: FAILED! => {"changed": true, "cmd": "nginx -s reload", "delta": "0:00:00.069230", "end": "2021-11-05 06:22:19.782802", "msg": "non-zero return code", "rc": 1, "start": "2021-11-05 06:22:19.713572", "stderr": "nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/fwz.ru.conf:117", "stderr_lines": ["nginx: [emerg] unknown log format \"main\" in /etc/nginx/sites-enabled/fwz.ru.conf:117"], "stdout": "", "stdout_lines": []}

Was try to install in new vps, but the same problem.

@pixlguru
thx, will check.

**Comment by spa086** [comment]
@pixlguru you was right, installation finished ok.  But now, when accessing the server, a 502 bad gateway error

**Comment by pixlguru** [comment]
if i remember correctly, there were some other tweaks necessary,
like docker volumes paths changed and old containers had to be removed,
good luck!

**Comment by dessalines** [comment]
Please let me know if there's anything missing, so I can document them on the migration section of this readme.

**Comment by applelhf** [comment]
> @spa086
> 如果我没有记错的话，还需要做一些其他调整，
> 就像docker卷路径更改和旧容器必须删除一样，
> 祝你好运！



> @spa086
> if i remember correctly, there were some other tweaks necessary,
> like docker volumes paths changed and old containers had to be removed,
> good luck!

Hello, my error is also 502 bad gateway error, but I did not find a solution. Can you tell me which need to be changed please?

**Comment by applelhf** [comment]
> @spa086
> if i remember correctly, there were some other tweaks necessary,
> like docker volumes paths changed and old containers had to be removed,
> good luck!

Hello, my error is also 502 bad gateway error, but I did not find a solution. Can you tell me which need to be changed please? my email is hoferlee@foxmail.com
