### ISSUE TITLE
Install instruction don't work

### ISSUE THREAD

**Issue by TurkeyMan** [LemmyNet/lemmy-ansible#42]
I have no idea what ansible is (sounds like the latest trendiest modern phone app for zoomers), and I'm trying to follow the instructions here, but they don't work. There seems to be critical information missing.

1. `<your-domain>` appears, but it doesn't say anywhere what it should be.
  Let's say I created a server accessible at `lemmy.mydomain.com`; is `<your-domain>` to be `lemmy.mydomain.com` or `mydomain.com`?
2. `config.hjson` is pretty minimal, there's no instructions to tell me what to change/add.
  In particular in `database`: `host: postgres` there's no machine with that hostname... why is that default? Not `localhost`?
3. `hosts` - Same question as above `myuser@example.com  domain=example.com`; should `domain` be `lemmy.mydomain.com` or `mydomain.com`?
4. I think I got the domain and stuff right by trial-and-error, but the install fails on a wall of unformatted json error dump about postgres stuff, of note: `error while creating mount source path '/srv/lemmy/lemmy.mydomain.com/volumes/postgres': mkdir /srv/lemmy: read-only file system`. I guess the script doesn't create a database... or it's trying to, but something's wrong and it's trying to act on a read-only filesystem?

So, am I supposed to create a database somewhere else? There's no words about this anywhere, and I can't find anybody else complaining about this either by google searching, so I'm obviously completely incompetent, or something went wrong in my config and database creation is failing with unhelpful messages?

I've just started trying random stuff; I've tried to install a database server instance, and set `host: localhost`, but it doesn't work, outputs the same error shown above. Messing with database users and stuff basically at random... no idea!

I'd suggest to update the install guide to clarify all these points.

Cheers.

---
EDIT:

For reference:
```
TASK [start docker-compose] ****************************************************************************************************************************************
fatal: [manu@lemmy.domain.com]: FAILED! => {"changed": false, "errors": ["ERROR: for lemmydomaincom_postgres_1  Cannot start service postgres: error while creating mount source path '/srv/lemmy/lemmy.domain.com/volumes/postgres': mkdir /srv/lemmy: read-only file system"], "module_stderr": "Starting lemmydomaincom_postgres_1 ... \nRecreating b308f746aab3_lemmydomaincom_pictrs_1 ... \nStarting lemmydomaincom_postgres_1              ... error\n\nERROR: for lemmydomaincom_postgres_1  Cannot start service postgres: error while creating mount source path '/srv/lemmy/lemmy.domain.com/volumes/postgres': mkdir /srv/lemmy: read-only file system\nRecreating b308f746aab3_lemmydomaincom_pictrs_1 ... error\n", "module_stdout": "", "msg": "Error starting project Encountered errors while bringing up the project."}
```

**Comment by TurkeyMan** [comment]
Why not dockerhub?

**Comment by Nutomic** [comment]
1. you need to set `lemmy.mydomain.com`
2. `host: postgres` refers to another docker container where lemmy runs. you can all possible config values [here](https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson)
3. also `lemmy.mydomain.com`
4. your ssh user doesnt seem to have permission to write to the target folder. it should execute with sudo by default, dont know why that isnt working.

If you dont like to use Ansible, there are also other installation methods (manual Docker installation, or from scratch without Docker).

https://join-lemmy.org/docs/en/administration/administration.html

**Comment by TurkeyMan** [comment]
I can see config KEYS, I have no indication of appropriate values for many of those fields.
So, you're saying that `host: postgres` is actually correct? There's another docker instance hidden in there? I never would have been able to guess that. I'll change that back and try again... but it wasn't working initially before I changed it.
My ssh user should have access, and when I login I seem to have manual access. I run the ansible script with `--become --ask-become-pass` business; without that, it doesn't work at all, with that, it seems to execute plenty of steps up to this point successfully, so it seems it does successfully become sudo.

**Comment by TurkeyMan** [comment]
Just to be clear, I should *not* install a postgres server and try and configure it? That should be automatic?
The script launches a postgres container with accounts and permissions configured correctly?

**Comment by TurkeyMan** [comment]
It still fails with the same permission problem... are we certain the script executes those commands as sudo? I supply the sudo password with `--become --ask-become-pass`, and the script runs up until that point.

**Comment by TurkeyMan** [comment]
I shelled in and executed `sudo docker-compose up -d`, and it succeeded... so, the ansible script seems to not execute that command sudo for some reason? Something else?

**Comment by TurkeyMan** [comment]
Okay, I deleted me VM instance and started over. It worked.
It seems that one initial failed attempt with the domain specified incorrectly poisoned every following install attempt despite correcting the mistake.

I still recommend acting on this ticket to make it a little more clear in the install guide. Might save someone the days of trial-and-error.

**Comment by Nutomic** [comment]
I'm not sure what exactly you would change in the install guide. I suggest you open a pull request with your proposed changes, then we can discuss and merge it.

**Comment by dessalines** [comment]
Let us know what specifically we need to change in these instructions, and we can reopen.
