### ISSUE TITLE
Add LEMMY_UI_CUSTOM_SCRIPT

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ansible#44]
Add the LEMMY_UI_CUSTOM_SCRIPT to setup.

**Comment by codyro** [comment]
This was renamed to `LEMMY_UI_CUSTOM_HTML_HEADER`, correct? I'll add the environmental variables listed [here](https://github.com/LemmyNet/lemmy-ui/#configuration) to be handled in the same way as `pict-rs` in #160 for the `lemmy-ui` VM.

**Comment by codyro** [comment]
Closing this as #160 will allow any environmental variable to be passed to the lemmy-ui container.
