### ISSUE TITLE
How to manage altered server configuration

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy-ansible#45]
Hello,
I see in the config file from Ansible this line:

https://github.com/LemmyNet/lemmy-ansible/blob/d4c1cd0a28acf0d245fc062f326001bfb2c036b1/templates/nginx.conf#L54

```
# Upload limit for pictrs
client_max_body_size 20M;
```

From what I can understand there is set that users can upload up to 20MB files, is that correct?

Since this seems excessive I wanted to lower the limit to 2MB. Having used Ansible as a method, can I manually edit the nginx configuration file on my server without having any conflicts whatsoever during the next release updates?

Thanks

**Comment by dessalines** [comment]
You might have to solve conflicts later when doing a git pull, but yes you can edit that as you see fit.

**Comment by Nutomic** [comment]
If you edit the file on the server, it will be overwritten next time you run ansible. Better edit it locally, then git will handle conflicts (or complain).

**Comment by skariko** [comment]
> If you edit the file on the server, it will be overwritten next time you run ansible. Better edit it locally, then git will handle conflicts (or complain).

Thanks a lot to both of you for the tips.

Being a beginner, to avoid problems during the updates I might think of temporarily modifying the file to 20M and then putting it back to 2M after the update, in this way it should not complain and it is an operation for a few seconds.

**Comment by Nutomic** [comment]
If you `git commit` in your local repo, and update with `git pull --rebase` it should work just fine, and your config is all in one place. You can even push it to your own git repository as backup. Worst case is that you get conflicts, but those should be easy to resolve.

Would be good to add this info to the readme/docs if you can confirm that it works (havent tried that exact thing myself).

**Comment by dessalines** [comment]
I don't think we should have to make a guide for this: a lot of people use git repos for their configs ( especially unix tools like tmux, vim distros, i3, etc ) and have to solve the merges on their own. I based this setup on matrix-docker-ansible-deploy, where your main configs are not checked in, so most cases solving conflicts isn't necessary.

@skariko if you need help solving git merge conflicts in the future, ask ppl in a linux chat or on stackoverflow.
