### ISSUE TITLE
Can I use Caddy a a reverse proxy

### ISSUE THREAD

**Issue by DokStook** [LemmyNet/lemmy-ansible#50]
Hello, 

I want to host my own lemmy instance but instead of using Nginx as a reverse proxy I want to use Caddy as a reverse proxy since it is easier. Is it possible to just reverse proxy localhost:1235 to my domain and be done with it or I have to do something else? 

Thanks in advance!

**Comment by dessalines** [comment]
I don't know anything about caddy, and we'll only support nginx with this deploy.
