### ISSUE TITLE
Use --become -K on update process when no using a key to authenticate 

### ISSUE THREAD

**Issue by calbasi** [LemmyNet/lemmy-ansible#51]
On the installation instructions of the README.md you have a useful note:

> Note: if you haven't set up ssh keys, and ssh using a password, use the command:
> ansible-playbook -i inventory/hosts lemmy.yml --become --ask-pass --ask-become-pass

I should be added in the Update instructions, because users updating are not reading the installation steps. Or, maybe, just make a reference to it.

In fact, for me, the right command is:

> ansible-playbook -i inventory/hosts lemmy.yml --become -K

Related: #23 #22 #15

**Comment by Nutomic** [comment]
Best make a pull request.

**Comment by dessalines** [comment]
If anyone knows of a good short link to ansible's ssh password and security related params, I'd rather link to then. There are tons of possibilities and this has to do with ansible, and how people are ssh'ing to their servers, not lemmy.

**Comment by ticoombs** [comment]
Redundant now. Already in the Readme. 

#close
