### ISSUE TITLE
Unable to apdate

### ISSUE THREAD

**Issue by DokStook** [LemmyNet/lemmy-ansible#54]
When I try to update using the steps mentioned in the README I get the error 

```

fatal: [redacted@redacted]: FAILED! => {"changed": false, "cmd": "apt-get install --no-install-recommends python-apt -y -q", "msg": "E: Package 'python-apt' has no installation candidate", "rc": 100, "stderr": "E: Package 'python-apt' has no installation candidate\n", "stderr_lines": ["E: Package 'python-apt' has no installation candidate"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage python-apt is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  python3-apt-dbg python3-apt python-apt-doc python-apt-common\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Package python-apt is not available, but is referred to by another package.", "This may mean that the package is missing, has been obsoleted, or", "is only available from another source", "However the following packages replace it:", "  python3-apt-dbg python3-apt python-apt-doc python-apt-common", ""]}

```

Looking at it I can see that there are other packages that are suggested instead of 'python-apt'. Should this be changed somewhere in the config?

**Comment by dessalines** [comment]
I don't know what distro you're using, but it looks like they removed python2.

Check the last line in these install instructions: https://github.com/LemmyNet/lemmy-ansible#install

**Comment by BrienJoseph** [comment]
https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

I would try to declare the python interpreter to your version of python. Had some trouble w/ this on porting over things from rhel7 to rhel8 on a different project via ansible playbooks.

**Comment by eslerm** [comment]
I reproduced this issue on Ubuntu 23.04 (Lunar). Ubuntu 22.04 LTS (Jammy) is not affected.

**Comment by dessalines** [comment]
Stale issue. Feel free to re-open if its still a problem.
