### ISSUE TITLE
Can't find documentation on how to do backups with Ansible setup

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy-ansible#55]
The backups section of the wiki seems to only be for docker installs and doesn't have information about how to do periodic backups after installing with Ansible

**Comment by dessalines** [comment]
@NIXOYE the bash backup script linked [here](https://join-lemmy.org/docs/en/administration/backup_and_restore.html) works the same for ansible installs as it does for docker, just use the right location (I think /src/lemmy/{server} ), and add that script to your cron after you test it.
