### ISSUE TITLE
Problems with new install

### ISSUE THREAD

**Issue by spa086** [LemmyNet/lemmy-ansible#6]
After trying a clean installation several times, according to the available documentation, I ran into a problem that after the installation was completed, when the server was contacted, an error 502 bade gate way appeared. Maybe I missed something, or the installation documentation is incomplete?

**Comment by Nutomic** [comment]
Check the docker-compose logs.

**Comment by spa086** [comment]
@Nutomic 

lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: https://lemmy:8536
lemmy-ui_1  | wsUri: wss://lemmy:8536/api/v3/ws
lemmy-ui_1  | isHttps: true
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy-ui_1  |
lemmy-ui_1  | /app/node_modules/node-fetch/lib/index.js:1461
lemmy-ui_1  |                   reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
lemmy-ui_1  |                          ^
lemmy-ui_1  | FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: getaddrinfo ENOTFOUND lemmy
lemmy-ui_1  |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
lemmy-ui_1  |     at ClientRequest.emit (node:events:390:28)
lemmy-ui_1  |     at Socket.socketErrorListener (node:_http_client:447:9)
lemmy-ui_1  |     at Socket.emit (node:events:390:28)
lemmy-ui_1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
lemmy-ui_1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
lemmy-ui_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
lemmy-ui_1  |   type: 'system',
lemmy-ui_1  |   errno: 'ENOTFOUND',
lemmy-ui_1  |   code: 'ENOTFOUND'
lemmy-ui_1  | }
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | Inferno is in development mode.
lemmy-ui_1  | httpbase: https://lemmy:8536
lemmy-ui_1  | wsUri: wss://lemmy:8536/api/v3/ws
lemmy-ui_1  | isHttps: true
lemmy-ui_1  | No JWT cookie found.
lemmy-ui_1  | http://0.0.0.0:1234
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | warning: invalid logging spec 'info"', ignoring it
lemmy_1     | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field `database`" near 20:16 }', src/main.rs:34:35
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pictrs_1    | Nov 07 14:01:16.318 ERROR sled::config: cache capacity is limited to the cgroup memory limit: 209715200 bytes
pictrs_1    | Nov 07 14:01:16.415  INFO actix_server::builder: Starting 1 workers
pictrs_1    | Nov 07 14:01:16.415  INFO actix_server::builder: Starting "actix-web-service-0.0.0.0:8080" service on 0.0.0.0:8080
postfix_1   | Starting Postfix Mail Transport Agent: postfix.
postfix_1   | rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="129" x-info="https://www.rsyslog.com"] start
postfix_1   | postfix/master[128]: daemon started -- version 3.4.14, configuration /etc/postfix
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | sh: locale: not found
postgres_1  | 2021-11-07 14:01:18.246 UTC [31] WARNING:  no usable system locales were found
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  | waiting for server to start....2021-11-07 14:01:21.644 UTC [37] LOG:  starting PostgreSQL 12.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
postgres_1  | 2021-11-07 14:01:21.647 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-11-07 14:01:21.739 UTC [38] LOG:  database system was shut down at 2021-11-07 14:01:21 UTC
postgres_1  | 2021-11-07 14:01:21.750 UTC [37] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | 2021-11-07 14:01:22.161 UTC [37] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down...2021-11-07 14:01:22.164 UTC [37] LOG:  aborting any active transactions
postgres_1  | 2021-11-07 14:01:22.170 UTC [37] LOG:  background worker "logical replication launcher" (PID 44) exited with exit code 1
postgres_1  | 2021-11-07 14:01:22.170 UTC [39] LOG:  shutting down
postgres_1  | .2021-11-07 14:01:22.185 UTC [37] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | 2021-11-07 14:01:22.332 UTC [1] LOG:  starting PostgreSQL 12.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
postgres_1  | 2021-11-07 14:01:22.334 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-11-07 14:01:22.336 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-11-07 14:01:22.339 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-11-07 14:01:22.404 UTC [51] LOG:  database system was shut down at 2021-11-07 14:01:22 UTC
postgres_1  | 2021-11-07 14:01:22.414 UTC [1] LOG:  database system is ready to accept connections

**Comment by dessalines** [comment]
`lemmy_1 | thread 'main' panicked at 'Couldn't initialize settings.: LemmyError { inner: "duplicate field database" near 20:16 }', src/main.rs:34:35`

You  added an extra database block to the one it tells you to copy from https://github.com/LemmyNet/lemmy-ansible/blob/main/examples/config.hjson
