### ISSUE TITLE
Error on the Task - Add Docker GPG apt Key

### ISSUE THREAD

**Issue by admiralarjun** [LemmyNet/lemmy-ansible#61]
TASK [Add Docker GPG apt Key] ***************************************************************

`fatal: [admin@<IP>]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "msg": "Unable to add a key from binary data", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory\ngpg: can't connect to the agent: No such file or directory\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: failed to start agent '/usr/bin/gpg-agent': No such file or directory", "gpg: can't connect to the agent: No such file or directory"], "stdout": "", "stdout_lines": []}`

**Comment by Nutomic** [comment]
Sounds like you need to install gpg or gpg-agent package.

**Comment by Nutomic** [comment]
You can also install docker-compose from official Ubuntu repos. To be honest I don't think there is any reason to use official Docker repository, especially if it causes problems like this.

**Comment by admiralarjun** [comment]
> You can also install docker-compose from official Ubuntu repos. To be honest I don't think there is any reason to use official Docker repository, especially if it causes problems like this.

Can i get the modified version of the playbook with this changes?

**Comment by Nutomic** [comment]
I made the change in #62. Let me know if it works with that.

**Comment by admiralarjun** [comment]
Thank You, anyway I managed to perform the installation by manually installing the docker and commenting the docker steps in the playbook.

**Comment by dessalines** [comment]
> stderr_lines": ["Shared connection to <ip>closed."], "stdout": "\u001b[33m\r0% [Working]\u001b[0m\r          
\rGet:1 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]\r\n\u001b[33m\r0%
[Connecting to archive.ubuntu.com]

I googled that error, and it looks like it has to do with either an old version of ansible on your system, or an old version of python on the target.

https://www.tecmint.com/fix-shared-connection-to-x-x-xx-closed-ansible-error/

**Comment by admiralarjun** [comment]
And, does Lemmy maintain any error logs? My instance's emails are not working. What could possibly go wrong? and I don't remember giving any SMPT details during the installation nor the setup

**Comment by admiralarjun** [comment]
I did my installation with ansible, where I make the changes now?

**Comment by dessalines** [comment]
inventory/host_vars/<your-domain>/config.hjson

https://github.com/LemmyNet/lemmy-ansible#install
