### ISSUE TITLE
cp examples/customPostgresql.conf inventory/customPostgresql.conf should point inside /inventory/host_vars

### ISSUE THREAD

**Issue by BillButter** [LemmyNet/lemmy-ansible#64]
cp examples/customPostgresql.conf inventory/customPostgresql.conf
should be
cp examples/customPostgresql.conf inventory/host_vars/{domain}/customPostgresql.conf

Or at least doing this fixed my problem

**Comment by dessalines** [comment]
Ah my bad, sorry about that.
