### ISSUE TITLE
TASK [start docker-compose] : Unable to load docker-compose

### ISSUE THREAD

**Issue by tifriis208** [LemmyNet/lemmy-ansible#67]
Hello,

On a fresh lemmy install on ubuntu server 22.04 (arm64 for raspberry pi and x64), I got this error (each time):
```
TASK [start docker-compose] ************************************************************************************************************************************************************
fatal: [user@IP_ADDRESS]: FAILED! => {"changed": false, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: Traceback (most recent call last):\n  File \"/tmp/ansible_docker_compose_payload_ixgojrhn/ansible_docker_compose_payload.zip/ansible_collections/community/docker/plugins/modules/docker_compose.py\", line 506, in <module>\nModuleNotFoundError: No module named 'compose'\n"}
```

For information, I also got this warning:
```
 TASK [Add Docker GPG apt Key] ******************************************************************************************************************
[WARNING]: Module remote_tmp /root/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as
another user. To avoid this, create the remote_tmp dir with the correct permissions manually
changed: [user@IP_ADDRESS]
```

Any idea how to run this playbook without error ?
Thanks :)

**Comment by tifriis208** [comment]
I try to install `ansible-galaxy collection install community.docker` but nothing change

**Comment by dessalines** [comment]
I've never tested this playbook on arm, so you might have to install docker manually on that machine, then skip the docker install steps in the playbook.

**Comment by tifriis208** [comment]
Thanks for your return. Indeed, the playbook only work for x86_64: 
  ```
- name: Install or upgrade docker-compose
    get_url: 
      url : "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64"
```

As raspberry pi is officialy supported in the documentation (`Supports arm64 / Raspberry Pi`), would you accept a pull request to modify this playbook according to [official docker documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)?

Thanks

**Comment by tifriis208** [comment]
I think this Pull Request should also solved this issue : https://github.com/LemmyNet/lemmy-ansible/pull/62

**Comment by dessalines** [comment]
Sure. 

#62 didn't work when I used a fresh ubuntu install, and no docker installation recommends you using the docker from the ubuntu repos.

**Comment by jonaharagon** [comment]
I am also seeing this same issue on a new Ubuntu 22.04 server that is **not** arm64, just regular x86_64.

**Comment by dessalines** [comment]
Hrm... I'm wondering if the script successfully installed docker on that machine. What does `sudo docker info` say there?

**Comment by jonaharagon** [comment]
Can't check right now, but Docker was installed and docker-compose was correctly located in /usr/local/bin.

All I had to do was run `pip install docker-compose` manually as Ansible suggested to get this working. Not sure why the compose download didn't work?

**Comment by jonaharagon** [comment]
Probably not, Hetzner Cloud images don't come with Docker installed. I think your process for installing `docker-compose` is outdated, what it looks like is Ansible is expecting to use docker-compose 2.x on [lemmy.yml#L167](https://github.com/LemmyNet/lemmy-ansible/blob/main/lemmy.yml#L167) (which gets installed to `/usr/libexec/docker/cli-plugins/`) and you're installing the old 1.x version to `/usr/local/bin` instead.

<details><summary># docker info</summary>
<code>Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-71-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.883GiB
 Name: lemmy
 ID: 7237f867-6d81-4a64-b219-e828d36a5018
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
</code></details>

**Comment by tifriis208** [comment]
I just test the new playbook (v1.2.0) on a fresh install on a raspberry pi4 with ubuntu 22.04 64 bit and no more issue with docker, thanks !
