### ISSUE TITLE
404 FetchError

### ISSUE THREAD

**Issue by mishari** [LemmyNet/lemmy-ansible#68]
I'm trying to setup a Lemmy installation at using Ansible
https://kaogeek.zymple.biz/

and I'm getting an error at 404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: getaddrinfo EAI_AGAIN lemmy

What could be causing this?

Thank you

Best regards,
Mishari

**Comment by Nutomic** [comment]
The site seems to work fine for me. Anyway if you still have problems, check the server logs for any error messages.

**Comment by ZackNash** [comment]
I'm getting a similar error:

 404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: getaddrinfo ENOTFOUND lemmy

Any help would be awesome.

**Comment by Nutomic** [comment]
This means the backend is down. Check the logs for any errors.

**Comment by ZackNash** [comment]
Where might I find the logs? Sorry I'm super new at this, definitely let me know if you don't have the time to walk me through it.

**Comment by ZackNash** [comment]
I figured it out. I messed up editing the hjson.config file. I should have left it as is from the example,. in case anyone else runs into this problem as well.

**Comment by mishari** [comment]
It seems that was an issue with the hosted postgres I was using. It's been fixed now thank you.

**Comment by ZackNash** [comment]
Oh ok cool, no problem! Thank you!
