### ISSUE TITLE
nginx conf looks like it's supposed to anonymize ips but it actually doesn't

### ISSUE THREAD

**Issue by Nothing4You** [LemmyNet/lemmy-ansible#70]
https://github.com/LemmyNet/lemmy-ansible/blob/c24e8a7137b852bb61ab9959c6110f3bcd99618e/templates/nginx.conf#L103-L111

this was originally in the initial commit in this repo intended to be anonymizing nginx logs, by cutting off the last bits of ips:
https://github.com/LemmyNet/lemmy-ansible/commit/80690afd1c24fd1d164001f8bfff0f748e794750#diff-8f9a7a73ce9c7de4398aaf3ca2224c97dfa796ef199ee4321e7f0b36d9f75162R106-R117

this was however never implemented properly in the first place, as discovered in #5, which changed the log format to `combined`.

the proper implementation, which would have used the custom log format, would have been `access_log /var/log/nginx/access.log lemmy_main;` instead of the originally committed `access_log /var/log/nginx/access.log main;`, or alternatively changing the custom log format name to `main` by using the following line:
```
log_format main '$remote_addr_anon - $remote_user [$time_local] "$request" '
'$status $body_bytes_sent "$http_referer" "$http_user_agent"';
```

in addition, if the intention is to actually anonymize ips, you should consider whether you want to forward non-anonymized ips to lemmy services, as they're currently receiving non-anonymized ips through `X-Real-IP $remote_addr` and `X-Forwarded-For $proxy_add_x_forwarded_for`.

if there is no intention to anonymize ips, you should remove the map from the config to avoid confusion.

**Comment by Nutomic** [comment]
True, better to keep things simple and remove it. Contributions welcome.
