### ISSUE TITLE
Update documentation to include Debian requirement

### ISSUE THREAD

**Issue by Zetaphor** [LemmyNet/lemmy-ansible#81]
This playbook assumes you're running on a Debian based linux distro. The readme only calls out "A VPS" as a requirement without specifying that it won't work in distros that don't use aptitude.

**Comment by Zetaphor** [comment]
Maybe this should be a separate issue, but support for non-debian distros would also be really nice

**Comment by HrBingR** [comment]
To add, the readme specifically says it can be used to deploy lemmy to "any server", which is quite misleading.

**Comment by christopher-conley** [comment]
> Maybe this should be a separate issue, but support for the larger non-debian server distros would also be really nice, ie: Fedora

I created a pull request that adds the ability for the Ansible playbook to run on rpm-based systems this morning:

[https://github.com/LemmyNet/lemmy-ansible/pull/88](https://github.com/LemmyNet/lemmy-ansible/pull/88)

I tested it on a couple VPS providers and it successfully deployed on Rocky Linux 8. You can pull [my forked repo down](https://github.com/christopher-conley/lemmy-ansible.git) and see if it works for you while we wait to see of the PR is approved.
