### ISSUE TITLE
Pictrs log file excessive

### ISSUE THREAD

**Issue by Hellhound1** [LemmyNet/lemmy-ansible#87]
Checking disk usage and can see pictrs log ("containerid"-json.log) is using 7.6gb of space in about 5 days.

Is anyone else able to check their log size to see this? Or is this unique to me? 

If this isnt just me, can a log size cap and log rotation be added to the docker compose file to prevent this? Or the default logging level be lowered in the script?

**Comment by dessalines** [comment]
Logging limits have been added now.
