### ISSUE TITLE
[Bug] Registration and emails not working since nginx config change

### ISSUE THREAD

**Issue by 0xAnansi** [LemmyNet/lemmy-ansible#94]
Hello,

seems that the recent split of nginx files broke something linked to the webservices used to send emails.

Now when trying to register with restricted registration, the following error happens in the main lemmy container:

```
2023-06-23T11:04:12.445148Z ERROR lemmy_server::api_routes_websocket: email_send_failed: Connection error: failed to lookup address information: Try again
0: lemmy_api_crud::user::create::perform
at crates/api_crud/src/user/create.rs:45
1: lemmy_server::root_span_builder::HTTP request
with http.method=GET http.scheme="http" http.host=0.0.0.0 http.target=/api/v3/ws otel.kind="server" request_id=36c786fe-de62-4202-9bf3-0b6718a2b9fa
at src/root_span_builder.rs:16
```

Seems that it's indeed the email sent to notify of a new registration requests that is broken.

As a side note, this breaks the request creation and no request appears in the admin validation panel.

It worked when I setup the instance yesterday, a few moments before the change of nginx configuration went live, and broke when I updated using the ansible recommended way, so this change is the likely culprit.

**Comment by dessalines** [comment]
Postfix might need to be moved into the internal networking block. I'm super busy right now, but could you work on this?

**Comment by 0xAnansi** [comment]
After discussing with some other admins in matrix, it seems that the change in configuration and my error where unfortunate coincidences. Closing the issue as false positive and sorry for the spam.
