### ISSUE TITLE
New internal nginx config breaks sites with an external icon. 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ansible#96]
One thing I didn't test with this setup: site icons.

We're getting this error on lemmygrad, with a site icon set:

`lemmy-ui_1  | FetchError: request to https://lemmygrad.ml/pictrs/image/fb9bc50e-58d5-434b-9b34-c08f6b7ae23d.png failed, reason: getaddrinfo EAI_AGAIN lemmygrad.ml`

I think this is because the internal node server doesn't have an external DNS, and can't access any external domains.

A temp fix was to do `update site set icon = null where id = 1;`

cc @SleeplessOne1917 @Nutomic

**Comment by Hellhound1** [comment]
It breaks all external DNS, including images held elsewhere by the looks of it, in my case Backblaze.

Thanks for the tip on removing the site icon, it allows the site to load again.

**Comment by binwiederhier** [comment]
There are at least 2 (3?) occurrences of of the new networking config in the playbook breaking. My site icon is not external (instance: https://discuss.ntfy.sh/). On my instance, I received "504 Gateways Timeout"s, and I couldn't get it to run at all. 

I reverted to the old ansible playbook with VERSION=0.18.0 set and that worked. There are more details in https://matrix.to/#/!OwmdVYiZSXrXbtCNLw:matrix.org?via=matrix.org&via=mozilla.org&via=tchncs.de -- Happy to provide more details too if need be.

**Comment by dessalines** [comment]
I'd really appreciate someone who knows a thing about docker networking to help us out with this one.

**Comment by dessalines** [comment]
I also tried that, but then on restarting lemmy-ui, it fails again.

**Comment by Hellhound1** [comment]
Ah yeah so it does. Removing the icon brings it right back to life.

**Comment by jtyszkiew** [comment]
Hello, idk if it will help, but I've added `lemmyexternalproxy` networks for the lemmy-ui and the pictrs, and it works now. Maybe it will help somehow

**Comment by Hellhound1** [comment]
@jtyszkiew can you restart lemmy-ui and let us know if it works on reboot?

I'm trying it now

**Comment by dessalines** [comment]
I've verified that adding `lemmyexternalproxy` to both, and restarting, does not fix the issue.

**Comment by jtyszkiew** [comment]
@dessalines do you see the white page with "Server error" message, or it's different problem?

**Comment by dessalines** [comment]
Same error, it just times out. To verify, you can do

`sudo docker-compose exec lemmy-ui sh`

```
/app
ping google.com
ping: bad address 'google.com'
```

**Comment by jtyszkiew** [comment]
```
/app # ping google.com
PING google.com (142.250.186.206): 56 data bytes
64 bytes from 142.250.186.206: seq=0 ttl=118 time=21.305 ms
64 bytes from 142.250.186.206: seq=1 ttl=118 time=21.380 ms
64 bytes from 142.250.186.206: seq=2 ttl=118 time=21.387 ms
64 bytes from 142.250.186.206: seq=3 ttl=118 time=21.460 ms
64 bytes from 142.250.186.206: seq=4 ttl=118 time=21.339 ms
64 bytes from 142.250.186.206: seq=5 ttl=118 time=21.336 ms
```

**Comment by dessalines** [comment]
Hrm... I'll try that, re-running the whole playbook. I was doing `docker-compose restart` before.

**Comment by dessalines** [comment]
Okay that was it, I needed to reboot the machine. Thank you all! 

I'll have a PR out in a sec.

**Comment by slash-zero** [comment]
> A temp fix was to do `update site set icon = null where id = 1;`
> 
> cc @SleeplessOne1917 @Nutomic

this was the only thing that fixed my site. Adding the external proxy network to both lemmy-ui and pictrs in docker-compose.yml appeared to have no impact, even after a —force-rebuild and server reboot. 

What is also odd is after removing the image icon from the DB, I was able to then add a new icon and it just worked…
